### ISSUE TITLE
French includes u+0178.  Does it have to?

### ISSUE THREAD

**Issue by SummerNightDream** [typekit/speakeasy#24]
https://github.com/typekit/speakeasy/blob/master/data/fr includes 376 (in hex, u+0178, LATIN CAPITAL LETTER Y WITH DIAERESIS).  Source Han Sans and Source Han Serif don't include this character.  Their font details pages at typekit.com don't show "French" on the supported languages list.
u+0178 was not included in ISO/IEC 8859-1. It was added to ISO/IEC 8859-15.
This character is rarely used according to https://en.wikipedia.org/wiki/ISO/IEC_8859-1.

**Comment by SummerNightDream** [comment]
u+0178 was not included in ISO/IEC 8859-1.  It was added to ISO/IEC 8859-15.  
Ken noted "The extent to which the _Source Han_ families support languages that use the Latin script is limited to those that can be supported via ISO/IEC 8859-1 (aka _ISO Latin 1_). Any additional Latin characters are for supporting Pinyin, Vietnamese, and transliteration methods for Japanese and Korean."

**Comment by frankrolf** [comment]
![IMG_3165](https://user-images.githubusercontent.com/2049645/67681833-6532a180-f98e-11e9-86ad-90f7ad80a54a.jpeg)
